import Head from 'next/head'
import styles from '../styles/Home.module.css'

import products from '../products.json'
import { fromImageToUrl } from './api/url'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
			{products.map(product => (
       <div key={product.name} className="">
        <div className="">
        <div className="flex flex-row w-40 h-40"><img src={fromImageToUrl(product.image)} alt="" /> </div>
	      <div className=""> {product.name} {product.price}
        </div>
        </div>
			</div>
			))}
    </div>
  )
}
